import { useCallback, useEffect, useRef, useState } from 'react';
import { API_BASE_URL } from '../../context/AdminContext.jsx';

const statuses = ['Pending', 'Loaded', 'In Transit', 'Delivered', 'Delayed', 'Cancelled'];
const payments = ['Unpaid', 'Partial', 'Paid'];
const methods = ['Company Truck', 'Third-Party Transport', 'Customer Pickup'];
const blankOrder = () => ({ order_no: '', route_hub: '', order_date: new Date().toISOString().slice(0, 10), salesperson: '', quantity: '', unit: '', customer_name: '', customer_phone: '', delivery_address: '', delivery_method: methods[0], driver: '', loading_date: '', loading_time: '', expected_delivery_date: '', actual_delivery_date: '', delivery_status: 'Pending', delay_reason: '', invoice_no: '', invoice_date: '', payment_status: 'Unpaid', payment_method: '', receipt_no: '', docs_complete: false, general_notes: '', driver_notes: '' });
const auth = () => ({ Authorization: `Bearer ${sessionStorage.getItem('admin_token') || ''}` });
async function api(path, options = {}) {
    const response = await fetch(`${API_BASE_URL}/admin/delivery-orders${path}`, { ...options, headers: { ...auth(), ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...options.headers } });
    if (options.raw) { if (!response.ok) throw new Error('Unable to download delivery orders'); return response.blob(); }
    const result = await response.json();
    if (!response.ok || result.success === false) throw new Error(result.message || `Request failed (${response.status})`);
    return result;
}
const dateText = value => value ? new Date(value).toLocaleDateString() : '—';
const statusTone = value => ({ Delivered: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20', 'In Transit': 'bg-sky-500/10 text-sky-300 border-sky-500/20', Loaded: 'bg-indigo-500/10 text-indigo-300 border-indigo-500/20', Delayed: 'bg-red-500/10 text-red-300 border-red-500/20', Cancelled: 'bg-zinc-500/10 text-zinc-400 border-zinc-500/20' }[value] || 'bg-amber-500/10 text-amber-300 border-amber-500/20');
const paymentTone = value => ({ Paid: 'bg-emerald-500/10 text-emerald-300', Partial: 'bg-amber-500/10 text-amber-300' }[value] || 'bg-red-500/10 text-red-300');
function Field({ label, name, value, onChange, type = 'text', options, multiline = false, required = false, placeholder = '' }) {
    const cls = 'w-full rounded-lg border border-white/8 bg-[#101014] px-3 py-2.5 text-sm text-zinc-100 outline-none focus:border-brand/60 placeholder:text-zinc-700';
    return <label className="block min-w-0"><span className="mb-1.5 block text-[11px] font-semibold text-zinc-500">{label}{required && <span className="text-red-400"> *</span>}</span>{options ? <select className={cls} value={value ?? ''} onChange={e => onChange(name, e.target.value)}>{options.map(option => <option key={option} value={option}>{option}</option>)}</select> : multiline ? <textarea className={`${cls} min-h-20 resize-y`} value={value ?? ''} onChange={e => onChange(name, e.target.value)} placeholder={placeholder} /> : <input className={cls} type={type} min={type === 'number' ? '0' : undefined} step={type === 'number' ? 'any' : undefined} value={value ?? ''} onChange={e => onChange(name, e.target.value)} placeholder={placeholder} required={required} />}</label>;
}

function OrderModal({ order, onClose, onSaved, onDeleted, notify }) {
    const [form, setForm] = useState(() => ({ ...blankOrder(), ...order, order_date: order?.order_date?.slice(0, 10) || blankOrder().order_date, loading_date: order?.loading_date?.slice(0, 10) || '', expected_delivery_date: order?.expected_delivery_date?.slice(0, 10) || '', actual_delivery_date: order?.actual_delivery_date?.slice(0, 10) || '', invoice_date: order?.invoice_date?.slice(0, 10) || '' }));
    const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const isEdit = Boolean(order?._id);
    const change = (key, value) => setForm(current => ({ ...current, [key]: value }));
    const save = async event => {
        event.preventDefault(); if (saving) return; setSaving(true); setError('');
        try { await api(isEdit ? `/${order._id}` : '', { method: isEdit ? 'PUT' : 'POST', body: JSON.stringify(form) }); notify(isEdit ? 'Delivery order updated' : 'Delivery order created'); onSaved(); }
        catch (e) { setError(e.message); } finally { setSaving(false); }
    };
    const remove = async () => { if (!window.confirm(`Delete ${form.order_no}?`)) return; setSaving(true); try { await api(`/${order._id}`, { method: 'DELETE' }); onDeleted(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
    const section = (title, fields, cols = 'sm:grid-cols-2') => <section className="space-y-3"><h3 className="border-b border-white/6 pb-2 text-[11px] font-black uppercase tracking-[.13em] text-brand">{title}</h3><div className={`grid grid-cols-1 ${cols} gap-3`}>{fields.map(f => <Field key={f.name} {...f} value={form[f.name]} onChange={change} />)}</div></section>;
    return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/75 p-3 backdrop-blur-sm sm:p-6" onMouseDown={e => e.target === e.currentTarget && onClose()}><form onSubmit={save} className="flex max-h-[94dvh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl border border-white/8 bg-[#17171b] shadow-2xl">
        <header className="flex items-center justify-between border-b border-white/6 px-5 py-4"><div><h2 className="text-base font-black text-white">{isEdit ? `Edit ${form.order_no}` : 'New Delivery Order'}</h2><p className="mt-1 text-xs text-zinc-500">Dispatch and customer details</p></div><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-lg bg-white/5 text-zinc-400 hover:text-white"><span className="material-icons">close</span></button></header>
        <div className="space-y-6 overflow-y-auto p-5">
            {section('Order Info', [{ name: 'order_no', label: 'Order Number', required: true, placeholder: 'SOHAR - 101' }, { name: 'order_date', label: 'Order Date', type: 'date', required: true }, { name: 'salesperson', label: 'Salesperson' }, { name: 'quantity', label: 'Quantity', type: 'number' }, { name: 'unit', label: 'Unit', placeholder: 'MTR, PCS, KG' }])}
            {section('Customer Information', [{ name: 'customer_name', label: 'Customer Name' }, { name: 'customer_phone', label: 'Phone' }, { name: 'delivery_address', label: 'Full Address', multiline: true }])}
            {section('Logistics & Dispatch', [{ name: 'route_hub', label: 'Route / Hub', placeholder: 'Auto-detected from order number' }, { name: 'delivery_method', label: 'Delivery Method', options: methods }, { name: 'driver', label: 'Driver / Courier' }, { name: 'loading_date', label: 'Loading Date', type: 'date' }, { name: 'loading_time', label: 'Loading Time', type: 'time' }, { name: 'expected_delivery_date', label: 'Expected Delivery', type: 'date' }, { name: 'actual_delivery_date', label: 'Actual Delivery', type: 'date' }, { name: 'delivery_status', label: 'Status', options: statuses }, { name: 'delay_reason', label: 'Delay Reason', multiline: true }])}
            {section('Financials & Accounting', [{ name: 'invoice_no', label: 'Invoice Number' }, { name: 'invoice_date', label: 'Invoice Date', type: 'date' }, { name: 'payment_status', label: 'Payment Status', options: payments }, { name: 'payment_method', label: 'Payment Method' }, { name: 'receipt_no', label: 'Receipt Number' }])}
            <label className="flex items-center gap-2 text-sm text-zinc-300"><input type="checkbox" checked={Boolean(form.docs_complete)} onChange={e => change('docs_complete', e.target.checked)} className="accent-[#B88E4B]" /> Documents complete</label>
            {section('Notes', [{ name: 'general_notes', label: 'General Notes', multiline: true }, { name: 'driver_notes', label: 'Driver Notes', multiline: true }])}
            {error && <p role="alert" className="rounded-lg border border-red-500/20 bg-red-500/10 px-3 py-2 text-sm text-red-300">{error}</p>}
        </div>
        <footer className="flex items-center gap-2 border-t border-white/6 px-5 py-4">{isEdit && <button type="button" disabled={saving} onClick={remove} className="mr-auto rounded-lg px-3 py-2 text-sm text-red-300 hover:bg-red-500/10">Delete</button>}<button type="button" disabled={saving} onClick={onClose} className="ml-auto rounded-lg bg-white/5 px-4 py-2 text-sm text-zinc-300 hover:bg-white/10">Cancel</button><button disabled={saving} className="rounded-lg bg-brand px-4 py-2 text-sm font-bold text-[#17130d] disabled:opacity-60">{saving ? 'Saving…' : isEdit ? 'Save Changes' : 'Create Order'}</button></footer>
    </form></div>;
}

export default function DeliveryTab() {
    const [orders, setOrders] = useState([]); const [stats, setStats] = useState({}); const [pagination, setPagination] = useState({ total: 0, page: 1, limit: 25, totalPages: 0 });
    const [filters, setFilters] = useState({ search: '', route: '', delivery_status: '', payment_status: '', date_from: '', date_to: '' }); const [searchInput, setSearchInput] = useState(''); const [sort, setSort] = useState({ by: 'order_date', dir: 'desc' });
    const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [modal, setModal] = useState(undefined); const [toast, setToast] = useState(''); const [busyId, setBusyId] = useState(''); const [lastUpdated, setLastUpdated] = useState(null); const fileRef = useRef(null); const loadRequestIdRef = useRef(0);
    const notify = useCallback(message => { setToast(message); window.setTimeout(() => setToast(''), 2800); }, []);
    useEffect(() => { const timer = window.setTimeout(() => setFilters(f => ({ ...f, search: searchInput })), 250); return () => window.clearTimeout(timer); }, [searchInput]);
    const load = useCallback(async ({ silent = false } = {}) => {
        const requestId = ++loadRequestIdRef.current;
        if (!silent) { setLoading(true); setError(''); }
        const params = new URLSearchParams({ page: pagination.page, limit: pagination.limit, sort_by: sort.by, sort_dir: sort.dir });
        Object.entries(filters).forEach(([key, value]) => value && params.set(key, value));
        try {
            const [list, summary] = await Promise.all([api(`?${params}`), api('/stats')]);
            if (requestId !== loadRequestIdRef.current) return;
            setOrders(list.data || []); setPagination(p => ({ ...p, ...list.pagination })); setStats(summary.data || {}); setLastUpdated(new Date());
        } catch (e) { if (!silent && requestId === loadRequestIdRef.current) setError(e.message); }
        finally { if (requestId === loadRequestIdRef.current) setLoading(false); }
    }, [filters, pagination.page, pagination.limit, sort]);
    useEffect(() => { load(); }, [load]);
    useEffect(() => {
        const intervalId = window.setInterval(() => load({ silent: true }), 18000);
        return () => window.clearInterval(intervalId);
    }, [load]);
    const routes = stats.routes || [];
    const setFilter = (key, value) => { setFilters(current => ({ ...current, [key]: value })); setPagination(current => ({ ...current, page: 1 })); };
    const changeSort = key => { setSort(current => ({ by: key, dir: current.by === key && current.dir === 'asc' ? 'desc' : 'asc' })); setPagination(current => ({ ...current, page: 1 })); };
    const quickStatus = async (event, order, status) => { event.stopPropagation(); setBusyId(order._id); try { await api(`/${order._id}/quick-status`, { method: 'PATCH', body: JSON.stringify({ delivery_status: status }) }); notify(`Marked ${order.order_no} as ${status}`); load(); } catch (e) { notify(e.message); } finally { setBusyId(''); } };
    const importCsv = async event => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; const data = new FormData(); data.append('file', file); try { const result = await api('/bulk-import', { method: 'POST', body: data }); const imported = result.data?.imported || 0; const errors = result.data?.errors || []; notify(`Imported ${imported} orders${errors.length ? ` · ${errors.length} row errors` : ''}`); if (errors.length) setError(errors.slice(0, 4).map(row => `Row ${row.row}: ${row.message}`).join(' | ')); load(); } catch (e) { notify(e.message); } };
    const exportCsv = async () => { try { const params = new URLSearchParams(); Object.entries(filters).forEach(([key, value]) => value && params.set(key, value)); params.set('sort_by', sort.by); params.set('sort_dir', sort.dir); const blob = await api(`/export?${params}`, { raw: true }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'delivery-orders.csv'; a.click(); URL.revokeObjectURL(url); } catch (e) { notify(e.message); } };
    const printSlip = order => { const w = window.open('', '_blank', 'width=800,height=900'); if (!w) return notify('Allow pop-ups to print the delivery slip'); const esc = text => String(text || '—').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c])); w.document.write(`<!doctype html><html><head><title>Delivery note ${esc(order.order_no)}</title><style>body{font:15px Arial,sans-serif;color:#222;padding:36px}header{display:flex;justify-content:space-between;border-bottom:3px solid #b88e4b;padding-bottom:18px}h1{margin:0;font-size:24px}.brand{color:#8c6831;font-weight:bold}table{width:100%;border-collapse:collapse;margin-top:28px}td{padding:12px;border:1px solid #ddd}td:first-child{font-weight:bold;background:#f7f5f0;width:32%}.sign{margin-top:70px;display:flex;justify-content:space-between}.sign span{width:40%;border-top:1px solid #777;padding-top:10px}@media print{button{display:none}}</style></head><body><header><div><h1>Delivery Note</h1><p class="brand">Al Najjar International</p></div><div><b>${esc(order.order_no)}</b><p>${esc(dateText(order.order_date))}</p></div></header><table>${[['Route / Hub', order.route_hub], ['Customer', order.customer_name], ['Phone', order.customer_phone], ['Delivery address', order.delivery_address], ['Quantity', `${order.quantity ?? '—'} ${order.unit || ''}`], ['Driver', order.driver], ['Expected delivery', dateText(order.expected_delivery_date)], ['Status', order.delivery_status], ['Invoice', order.invoice_no], ['Driver notes', order.driver_notes]].map(([label, value]) => `<tr><td>${esc(label)}</td><td>${esc(value)}</td></tr>`).join('')}</table><div class="sign"><span>Received by</span><span>Driver signature</span></div><script>window.onload=()=>window.print()</script></body></html>`); w.document.close(); };
    const cardItems = [['Total Orders', stats.total_orders], ['In Progress', stats.in_progress], ['Delivered', stats.delivered], ['Delayed', stats.delayed], ['Unpaid / Partial', stats.unpaid_or_partial]];
    const headers = [['route_hub', 'Route / Hub'], ['order_no', 'Order No'], ['order_date', 'Order Date'], ['customer_name', 'Customer'], ['delivery_status', 'Status'], ['quantity', 'Qty'], ['expected_delivery_date', 'Expected Date'], ['payment_status', 'Payment'], ['driver', 'Driver']];
    return <div className="space-y-5" dir="auto">
        <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="mb-1 text-[10px] font-black uppercase tracking-[.2em] text-brand">Al Najjar · Logistics</p><h1 className="text-2xl font-black text-white">Dispatch Board <span className="text-zinc-500">/ إدارة التوصيل والتوزيع</span></h1><p className="mt-1 text-sm text-zinc-500">Manage deliveries, routes, drivers, and payment status.</p></div><div className="flex flex-wrap items-center justify-end gap-2"><span className="text-[10px] text-zinc-500">Updated {lastUpdated ? lastUpdated.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : '—'}</span><button type="button" onClick={() => load({ silent: true })} aria-label="Refresh delivery data" title="Refresh Data" className="grid h-10 w-10 place-items-center rounded-lg border border-white/8 bg-white/[.03] text-zinc-400 hover:bg-white/[.07] hover:text-brand"><span className="material-icons text-[18px]">refresh</span></button><button onClick={() => setModal(null)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand px-4 py-2.5 text-sm font-black text-[#18140d] hover:bg-brand-light"><span className="material-icons text-[18px]">add</span>New Order</button></div></div>
        <div className="grid grid-cols-2 gap-3 xl:grid-cols-5">{cardItems.map(([label, value], i) => <div key={label} className="rounded-xl border border-white/6 bg-[#151519] p-4"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-zinc-500">{label}</p><span className={`material-icons text-[18px] ${i === 3 ? 'text-red-300' : i === 2 ? 'text-emerald-300' : 'text-brand'}`}>{['receipt_long', 'local_shipping', 'task_alt', 'warning', 'payments'][i]}</span></div><p className="mt-3 text-2xl font-black text-white">{value ?? 0}</p></div>)}</div>
        <div className="flex flex-col gap-3 rounded-xl border border-white/6 bg-[#151519] p-3 xl:flex-row xl:items-center"><label className="relative min-w-52 flex-1"><span className="material-icons absolute left-3 top-1/2 -translate-y-1/2 text-[18px] text-zinc-600">search</span><input value={searchInput} onChange={e => setSearchInput(e.target.value)} placeholder="Search orders, customers, drivers…" className="w-full rounded-lg border border-white/8 bg-[#101014] py-2.5 pl-10 pr-3 text-sm text-white outline-none focus:border-brand/50" /></label>
            <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 xl:flex"><select aria-label="Route" value={filters.route} onChange={e => setFilter('route', e.target.value)} className="rounded-lg border border-white/8 bg-[#101014] px-3 py-2 text-xs text-zinc-300"><option value="">All routes</option>{routes.map(route => <option key={route}>{route}</option>)}</select><select aria-label="Delivery status" value={filters.delivery_status} onChange={e => setFilter('delivery_status', e.target.value)} className="rounded-lg border border-white/8 bg-[#101014] px-3 py-2 text-xs text-zinc-300"><option value="">All statuses</option>{statuses.map(status => <option key={status}>{status}</option>)}</select><select aria-label="Payment status" value={filters.payment_status} onChange={e => setFilter('payment_status', e.target.value)} className="rounded-lg border border-white/8 bg-[#101014] px-3 py-2 text-xs text-zinc-300"><option value="">All payments</option>{payments.map(status => <option key={status}>{status}</option>)}</select><div className="flex gap-1"><input aria-label="Date from" type="date" value={filters.date_from} onChange={e => setFilter('date_from', e.target.value)} className="min-w-0 rounded-lg border border-white/8 bg-[#101014] px-2 py-2 text-[11px] text-zinc-400" /><input aria-label="Date to" type="date" value={filters.date_to} onChange={e => setFilter('date_to', e.target.value)} className="min-w-0 rounded-lg border border-white/8 bg-[#101014] px-2 py-2 text-[11px] text-zinc-400" /></div></div>
            <div className="flex gap-2"><input ref={fileRef} type="file" accept=".csv,text/csv" className="hidden" onChange={importCsv} /><button onClick={() => fileRef.current?.click()} className="flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-white/8 px-3 py-2 text-xs font-semibold text-zinc-300 hover:bg-white/5"><span className="material-icons text-[16px]">upload_file</span>Import CSV</button><button onClick={exportCsv} className="flex flex-1 items-center justify-center gap-1.5 rounded-lg border border-white/8 px-3 py-2 text-xs font-semibold text-zinc-300 hover:bg-white/5"><span className="material-icons text-[16px]">download</span>Export</button></div>
        </div>
        {error && <div role="alert" className="flex items-center justify-between gap-3 rounded-lg border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-200"><span>{error}</span><button onClick={() => setError('')} className="material-icons text-base">close</button></div>}
        <div className="overflow-hidden rounded-xl border border-white/6 bg-[#151519]"><div className="overflow-x-auto"><table className="w-full min-w-[1120px] border-collapse text-left"><thead><tr className="border-b border-white/6 bg-white/[.02]">{headers.map(([key, label]) => <th key={key} className="px-4 py-3 text-[10px] font-black uppercase tracking-wider text-zinc-500"><button onClick={() => changeSort(key)} className="inline-flex items-center gap-1 hover:text-zinc-200">{label}<span className="material-icons text-[13px]">{sort.by === key ? sort.dir === 'asc' ? 'arrow_upward' : 'arrow_downward' : 'unfold_more'}</span></button></th>)}<th className="px-4 py-3 text-[10px] font-black uppercase tracking-wider text-zinc-500">Actions</th></tr></thead>
            <tbody>{loading ? <tr><td colSpan="10" className="py-16 text-center text-sm text-zinc-500"><span className="material-icons mb-2 block animate-spin text-brand">refresh</span>Loading deliveries…</td></tr> : orders.length === 0 ? <tr><td colSpan="10" className="py-16 text-center"><span className="material-icons mb-2 block text-3xl text-zinc-700">local_shipping</span><p className="text-sm font-semibold text-zinc-400">No delivery orders found</p><p className="mt-1 text-xs text-zinc-600">Create an order to start tracking dispatch.</p></td></tr> : orders.map(order => <tr key={order._id} onClick={() => setModal(order)} className="cursor-pointer border-b border-white/[.035] transition-colors hover:bg-white/[.025]">
                <td className="px-4 py-3"><span className="rounded-md bg-brand/10 px-2 py-1 text-[10px] font-black text-brand">{order.route_hub || '—'}</span></td><td className="px-4 py-3 text-xs font-bold text-white">{order.order_no}</td><td className="px-4 py-3 text-xs text-zinc-400">{dateText(order.order_date)}</td><td className="px-4 py-3"><p className="max-w-44 truncate text-xs font-bold text-zinc-200">{order.customer_name || '—'}</p><div className="mt-1 flex items-center gap-2 text-[10px] text-zinc-500">{order.customer_phone && <><a onClick={e => e.stopPropagation()} className="hover:text-brand" href={`tel:${order.customer_phone}`} title="Call customer"><span className="material-icons align-middle text-[13px]">call</span> {order.customer_phone}</a><a onClick={e => e.stopPropagation()} className="text-emerald-400 hover:text-emerald-300" href={`https://wa.me/${order.customer_phone.replace(/\D/g, '')}?text=${encodeURIComponent(`Hello ${order.customer_name || ''}, regarding order ${order.order_no}`)}`} target="_blank" rel="noreferrer" title="WhatsApp"><span className="material-icons align-middle text-[13px]">chat</span></a></>}{order.delivery_address && <a onClick={e => e.stopPropagation()} href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(order.delivery_address)}`} target="_blank" rel="noreferrer" title={order.delivery_address} className="text-brand hover:text-brand-light"><span className="material-icons align-middle text-[13px]">location_on</span></a>}</div></td>
                <td className="px-4 py-3" onClick={e => e.stopPropagation()}><select disabled={busyId === order._id} value={order.delivery_status} onChange={e => quickStatus(e, order, e.target.value)} className={`max-w-32 rounded-full border px-2 py-1 text-[10px] font-bold outline-none ${statusTone(order.delivery_status)} disabled:opacity-50`}>{statuses.map(status => <option key={status}>{status}</option>)}</select></td><td className="px-4 py-3 text-xs text-zinc-300">{order.quantity ?? '—'} <span className="text-zinc-600">{order.unit}</span></td><td className="px-4 py-3 text-xs text-zinc-400">{dateText(order.expected_delivery_date)}</td><td className="px-4 py-3"><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${paymentTone(order.payment_status)}`}>{order.payment_status}</span></td><td className="px-4 py-3 text-xs text-zinc-400">{order.driver || '—'}</td><td className="px-4 py-3" onClick={e => e.stopPropagation()}><button onClick={() => printSlip(order)} title="Print delivery note" className="grid h-8 w-8 place-items-center rounded-lg bg-white/5 text-zinc-400 hover:bg-brand/15 hover:text-brand"><span className="material-icons text-[17px]">print</span></button></td>
            </tr>)}</tbody></table></div>
            <div className="flex flex-col justify-between gap-3 border-t border-white/6 px-4 py-3 sm:flex-row sm:items-center"><span className="text-xs text-zinc-500">{pagination.total ? `${(pagination.page - 1) * pagination.limit + 1}–${Math.min(pagination.page * pagination.limit, pagination.total)} of ${pagination.total}` : '0 orders'}</span><div className="flex items-center gap-2"><select value={pagination.limit} onChange={e => setPagination(p => ({ ...p, limit: Number(e.target.value), page: 1 }))} className="rounded-lg border border-white/8 bg-[#101014] px-2 py-1.5 text-xs text-zinc-400"><option value="25">25 / page</option><option value="50">50 / page</option><option value="100">100 / page</option></select><button disabled={pagination.page <= 1 || loading} onClick={() => setPagination(p => ({ ...p, page: p.page - 1 }))} className="grid h-8 w-8 place-items-center rounded-lg bg-white/5 text-zinc-300 disabled:opacity-30"><span className="material-icons text-[17px]">chevron_left</span></button><span className="min-w-16 text-center text-xs text-zinc-400">Page {pagination.page} / {Math.max(1, pagination.totalPages)}</span><button disabled={pagination.page >= pagination.totalPages || loading} onClick={() => setPagination(p => ({ ...p, page: p.page + 1 }))} className="grid h-8 w-8 place-items-center rounded-lg bg-white/5 text-zinc-300 disabled:opacity-30"><span className="material-icons text-[17px]">chevron_right</span></button></div></div>
        </div>
        {modal !== undefined && <OrderModal order={modal} onClose={() => setModal(undefined)} onSaved={() => { setModal(undefined); load(); }} onDeleted={() => { setModal(undefined); notify('Delivery order deleted'); load(); }} notify={notify} />}
        {toast && <div role="status" className="fixed bottom-5 right-5 z-[90] max-w-sm rounded-xl border border-emerald-500/20 bg-[#10231b] px-4 py-3 text-sm text-emerald-200 shadow-2xl">{toast}</div>}
    </div>;
}
